pre-commit: update black, black-docs version
typed-ast is not maintained anymore, and builds with newer python
versions raises:

  ast27/Custom/../Include/compile.h:12:12: error: unknown type name ‘PyFutureFeatures’
     12 | PyAPI_FUNC(PyFutureFeatures *) PyFuture_FromAST(struct _mod *, const char *);

The minimum black version with 966baaa is 21.4b0,
but due to black-docs min version with the same fix (a24ed2d, 1.13.0),
set as 22.12.0.

Signed-off-by: Jorge Marques <jorge.marques@analog.com>